const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/data/reactions.ts');
let content = fs.readFileSync(filePath, 'utf8');

const reactionsStartMatch = content.match(/export const reactions: Reaction\[\] = \[/);
const reactionsStartIndex = reactionsStartMatch.index + reactionsStartMatch[0].length;

const lostReactions = [
  { id:'auto_Li_F2', reactants:["Li","F2"], eq:'Li + F2 → LiF', balanced:'2Li + F2 → 2LiF', products:["LiF"], type:'synthesis', visual:'spark', color:'hsl(0,70%,60%)', enthalpy:-400, desc:'Li reacts with F2 to form LiF.', realUse:'Salt formation' },
  { id:'auto_Li_Cl2', reactants:["Li","Cl2"], eq:'Li + Cl2 → LiCl', balanced:'2Li + Cl2 → 2LiCl', products:["LiCl"], type:'synthesis', visual:'spark', color:'hsl(0,70%,60%)', enthalpy:-400, desc:'Li reacts with Cl2 to form LiCl.', realUse:'Salt formation' },
  { id:'auto_Li_Br2', reactants:["Li","Br2"], eq:'Li + Br2 → LiBr', balanced:'2Li + Br2 → 2LiBr', products:["LiBr"], type:'synthesis', visual:'spark', color:'hsl(0,70%,60%)', enthalpy:-400, desc:'Li reacts with Br2 to form LiBr.', realUse:'Salt formation' },
  { id:'auto_Li_I2', reactants:["Li","I2"], eq:'Li + I2 → LiI', balanced:'2Li + I2 → 2LiI', products:["LiI"], type:'synthesis', visual:'spark', color:'hsl(0,70%,60%)', enthalpy:-400, desc:'Li reacts with I2 to form LiI.', realUse:'Salt formation' },
  { id:'auto_Na_F2', reactants:["Na","F2"], eq:'Na + F2 → NaF', balanced:'2Na + F2 → 2NaF', products:["NaF"], type:'synthesis', visual:'spark', color:'hsl(45,90%,60%)', enthalpy:-400, desc:'Na reacts with F2 to form NaF.', realUse:'Salt formation' },
  { id:'auto_Na_Cl2', reactants:["Na","Cl2"], eq:'Na + Cl2 → NaCl', balanced:'2Na + Cl2 → 2NaCl', products:["NaCl"], type:'synthesis', visual:'spark', color:'hsl(45,90%,60%)', enthalpy:-400, desc:'Na reacts with Cl2 to form NaCl.', realUse:'Salt formation' },
  { id:'auto_Na_Br2', reactants:["Na","Br2"], eq:'Na + Br2 → NaBr', balanced:'2Na + Br2 → 2NaBr', products:["NaBr"], type:'synthesis', visual:'spark', color:'hsl(45,90%,60%)', enthalpy:-400, desc:'Na reacts with Br2 to form NaBr.', realUse:'Salt formation' },
  { id:'auto_Na_I2', reactants:["Na","I2"], eq:'Na + I2 → NaI', balanced:'2Na + I2 → 2NaI', products:["NaI"], type:'synthesis', visual:'spark', color:'hsl(45,90%,60%)', enthalpy:-400, desc:'Na reacts with I2 to form NaI.', realUse:'Salt formation' },
  { id:'auto_K_F2', reactants:["K","F2"], eq:'K + F2 → KF', balanced:'2K + F2 → 2KF', products:["KF"], type:'synthesis', visual:'spark', color:'hsl(280,60%,65%)', enthalpy:-400, desc:'K reacts with F2 to form KF.', realUse:'Salt formation' },
  { id:'auto_K_Cl2', reactants:["K","Cl2"], eq:'K + Cl2 → KCl', balanced:'2K + Cl2 → 2KCl', products:["KCl"], type:'synthesis', visual:'spark', color:'hsl(280,60%,65%)', enthalpy:-400, desc:'K reacts with Cl2 to form KCl.', realUse:'Salt formation' },
  { id:'auto_K_Br2', reactants:["K","Br2"], eq:'K + Br2 → KBr', balanced:'2K + Br2 → 2KBr', products:["KBr"], type:'synthesis', visual:'spark', color:'hsl(280,60%,65%)', enthalpy:-400, desc:'K reacts with Br2 to form KBr.', realUse:'Salt formation' },
  { id:'auto_K_I2', reactants:["K","I2"], eq:'K + I2 → KI', balanced:'2K + I2 → 2KI', products:["KI"], type:'synthesis', visual:'spark', color:'hsl(280,60%,65%)', enthalpy:-400, desc:'K reacts with I2 to form KI.', realUse:'Salt formation' },
  { id:'auto_Rb_F2', reactants:["Rb","F2"], eq:'Rb + F2 → RbF', balanced:'2Rb + F2 → 2RbF', products:["RbF"], type:'synthesis', visual:'spark', color:'hsl(340,60%,55%)', enthalpy:-400, desc:'Rb reacts with F2 to form RbF.', realUse:'Salt formation' },
  { id:'auto_Rb_Cl2', reactants:["Rb","Cl2"], eq:'Rb + Cl2 → RbCl', balanced:'2Rb + Cl2 → 2RbCl', products:["RbCl"], type:'synthesis', visual:'spark', color:'hsl(340,60%,55%)', enthalpy:-400, desc:'Rb reacts with Cl2 to form RbCl.', realUse:'Salt formation' },
  { id:'auto_Rb_Br2', reactants:["Rb","Br2"], eq:'Rb + Br2 → RbBr', balanced:'2Rb + Br2 → 2RbBr', products:["RbBr"], type:'synthesis', visual:'spark', color:'hsl(340,60%,55%)', enthalpy:-400, desc:'Rb reacts with Br2 to form RbBr.', realUse:'Salt formation' },
  { id:'auto_Rb_I2', reactants:["Rb","I2"], eq:'Rb + I2 → RbI', balanced:'2Rb + I2 → 2RbI', products:["RbI"], type:'synthesis', visual:'spark', color:'hsl(340,60%,55%)', enthalpy:-400, desc:'Rb reacts with I2 to form RbI.', realUse:'Salt formation' },
  { id:'auto_Cs_F2', reactants:["Cs","F2"], eq:'Cs + F2 → CsF', balanced:'2Cs + F2 → 2CsF', products:["CsF"], type:'synthesis', visual:'spark', color:'hsl(200,70%,55%)', enthalpy:-400, desc:'Cs reacts with F2 to form CsF.', realUse:'Salt formation' },
  { id:'auto_Cs_Cl2', reactants:["Cs","Cl2"], eq:'Cs + Cl2 → CsCl', balanced:'2Cs + Cl2 → 2CsCl', products:["CsCl"], type:'synthesis', visual:'spark', color:'hsl(200,70%,55%)', enthalpy:-400, desc:'Cs reacts with Cl2 to form CsCl.', realUse:'Salt formation' },
  { id:'auto_Cs_Br2', reactants:["Cs","Br2"], eq:'Cs + Br2 → CsBr', balanced:'2Cs + Br2 → 2CsBr', products:["CsBr"], type:'synthesis', visual:'spark', color:'hsl(200,70%,55%)', enthalpy:-400, desc:'Cs reacts with Br2 to form CsBr.', realUse:'Salt formation' },
  { id:'auto_Cs_I2', reactants:["Cs","I2"], eq:'Cs + I2 → CsI', balanced:'2Cs + I2 → 2CsI', products:["CsI"], type:'synthesis', visual:'spark', color:'hsl(200,70%,55%)', enthalpy:-400, desc:'Cs reacts with I2 to form CsI.', realUse:'Salt formation' },
  { id:'auto_Be_F2', reactants:["Be","F2"], eq:'Be + F2 → BeF2', balanced:'Be + F2 → BeF2', products:["BeF2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,85%)', enthalpy:-600, desc:'Be reacts with F2 to form BeF2.', realUse:'Halide formation' },
  { id:'auto_Be_Cl2', reactants:["Be","Cl2"], eq:'Be + Cl2 → BeCl2', balanced:'Be + Cl2 → BeCl2', products:["BeCl2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,85%)', enthalpy:-600, desc:'Be reacts with Cl2 to form BeCl2.', realUse:'Halide formation' },
  { id:'auto_Be_Br2', reactants:["Be","Br2"], eq:'Be + Br2 → BeBr2', balanced:'Be + Br2 → BeBr2', products:["BeBr2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,85%)', enthalpy:-600, desc:'Be reacts with Br2 to form BeBr2.', realUse:'Halide formation' },
  { id:'auto_Be_I2', reactants:["Be","I2"], eq:'Be + I2 → BeI2', balanced:'Be + I2 → BeI2', products:["BeI2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,85%)', enthalpy:-600, desc:'Be reacts with I2 to form BeI2.', realUse:'Halide formation' },
  { id:'auto_Mg_F2', reactants:["Mg","F2"], eq:'Mg + F2 → MgF2', balanced:'Mg + F2 → MgF2', products:["MgF2"], type:'synthesis', visual:'smoke', color:'hsl(120,50%,60%)', enthalpy:-600, desc:'Mg reacts with F2 to form MgF2.', realUse:'Halide formation' },
  { id:'auto_Mg_Cl2', reactants:["Mg","Cl2"], eq:'Mg + Cl2 → MgCl2', balanced:'Mg + Cl2 → MgCl2', products:["MgCl2"], type:'synthesis', visual:'smoke', color:'hsl(120,50%,60%)', enthalpy:-600, desc:'Mg reacts with Cl2 to form MgCl2.', realUse:'Halide formation' },
  { id:'auto_Mg_Br2', reactants:["Mg","Br2"], eq:'Mg + Br2 → MgBr2', balanced:'Mg + Br2 → MgBr2', products:["MgBr2"], type:'synthesis', visual:'smoke', color:'hsl(120,50%,60%)', enthalpy:-600, desc:'Mg reacts with Br2 to form MgBr2.', realUse:'Halide formation' },
  { id:'auto_Mg_I2', reactants:["Mg","I2"], eq:'Mg + I2 → MgI2', balanced:'Mg + I2 → MgI2', products:["MgI2"], type:'synthesis', visual:'smoke', color:'hsl(120,50%,60%)', enthalpy:-600, desc:'Mg reacts with I2 to form MgI2.', realUse:'Halide formation' },
  { id:'auto_Ca_F2', reactants:["Ca","F2"], eq:'Ca + F2 → CaF2', balanced:'Ca + F2 → CaF2', products:["CaF2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,90%)', enthalpy:-600, desc:'Ca reacts with F2 to form CaF2.', realUse:'Halide formation' },
  { id:'auto_Ca_Cl2', reactants:["Ca","Cl2"], eq:'Ca + Cl2 → CaCl2', balanced:'Ca + Cl2 → CaCl2', products:["CaCl2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,90%)', enthalpy:-600, desc:'Ca reacts with Cl2 to form CaCl2.', realUse:'Halide formation' },
  { id:'auto_Ca_Br2', reactants:["Ca","Br2"], eq:'Ca + Br2 → CaBr2', balanced:'Ca + Br2 → CaBr2', products:["CaBr2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,90%)', enthalpy:-600, desc:'Ca reacts with Br2 to form CaBr2.', realUse:'Halide formation' },
  { id:'auto_Ca_I2', reactants:["Ca","I2"], eq:'Ca + I2 → CaI2', balanced:'Ca + I2 → CaI2', products:["CaI2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,90%)', enthalpy:-600, desc:'Ca reacts with I2 to form CaI2.', realUse:'Halide formation' },
  { id:'auto_Sr_F2', reactants:["Sr","F2"], eq:'Sr + F2 → SrF2', balanced:'Sr + F2 → SrF2', products:["SrF2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,85%)', enthalpy:-600, desc:'Sr reacts with F2 to form SrF2.', realUse:'Halide formation' },
  { id:'auto_Sr_Cl2', reactants:["Sr","Cl2"], eq:'Sr + Cl2 → SrCl2', balanced:'Sr + Cl2 → SrCl2', products:["SrCl2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,85%)', enthalpy:-600, desc:'Sr reacts with Cl2 to form SrCl2.', realUse:'Halide formation' },
  { id:'auto_Sr_Br2', reactants:["Sr","Br2"], eq:'Sr + Br2 → SrBr2', balanced:'Sr + Br2 → SrBr2', products:["SrBr2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,85%)', enthalpy:-600, desc:'Sr reacts with Br2 to form SrBr2.', realUse:'Halide formation' },
  { id:'auto_Sr_I2', reactants:["Sr","I2"], eq:'Sr + I2 → SrI2', balanced:'Sr + I2 → SrI2', products:["SrI2"], type:'synthesis', visual:'smoke', color:'hsl(0,0%,85%)', enthalpy:-600, desc:'Sr reacts with I2 to form SrI2.', realUse:'Halide formation' },
  { id:'auto_Ba_F2', reactants:["Ba","F2"], eq:'Ba + F2 → BaF2', balanced:'Ba + F2 → BaF2', products:["BaF2"], type:'synthesis', visual:'smoke', color:'hsl(120,60%,50%)', enthalpy:-600, desc:'Ba reacts with F2 to form BaF2.', realUse:'Halide formation' },
  { id:'auto_Ba_Cl2', reactants:["Ba","Cl2"], eq:'Ba + Cl2 → BaCl2', balanced:'Ba + Cl2 → BaCl2', products:["BaCl2"], type:'synthesis', visual:'smoke', color:'hsl(120,60%,50%)', enthalpy:-600, desc:'Ba reacts with Cl2 to form BaCl2.', realUse:'Halide formation' },
  { id:'auto_Ba_Br2', reactants:["Ba","Br2"], eq:'Ba + Br2 → BaBr2', balanced:'Ba + Br2 → BaBr2', products:["BaBr2"], type:'synthesis', visual:'smoke', color:'hsl(120,60%,50%)', enthalpy:-600, desc:'Ba reacts with Br2 to form BaBr2.', realUse:'Halide formation' },
  { id:'auto_Ba_I2', reactants:["Ba","I2"], eq:'Ba + I2 → BaI2', balanced:'Ba + I2 → BaI2', products:["BaI2"], type:'synthesis', visual:'smoke', color:'hsl(120,60%,50%)', enthalpy:-600, desc:'Ba reacts with I2 to form BaI2.', realUse:'Halide formation' },
  { id:'auto_HCl_NaOH', reactants:["HCl","NaOH"], eq:'HCl + NaOH → NaCl + H2O', balanced:'HCl + NaOH → NaCl + H₂O', products:["NaCl","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HCl with NaOH.', realUse:'Salt production' },
  { id:'auto_HCl_KOH', reactants:["HCl","KOH"], eq:'HCl + KOH → KCl + H2O', balanced:'HCl + KOH → KCl + H₂O', products:["KCl","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HCl with KOH.', realUse:'Salt production' },
  { id:'auto_HCl_LiOH', reactants:["HCl","LiOH"], eq:'HCl + LiOH → LiCl + H2O', balanced:'HCl + LiOH → LiCl + H₂O', products:["LiCl","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HCl with LiOH.', realUse:'Salt production' },
  { id:'auto_HCl_Ca(OH)2', reactants:["HCl","Ca(OH)2"], eq:'HCl + Ca(OH)2 → CaCl2 + H2O', balanced:'₂HCl + Ca(OH)₂ → CaCl₂ + ₂H₂O', products:["CaCl2","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HCl with Ca(OH)2.', realUse:'Salt production' },
  { id:'auto_HCl_Mg(OH)2', reactants:["HCl","Mg(OH)2"], eq:'HCl + Mg(OH)2 → MgCl2 + H2O', balanced:'₂HCl + Mg(OH)₂ → MgCl₂ + ₂H₂O', products:["MgCl2","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HCl with Mg(OH)2.', realUse:'Salt production' },
  { id:'auto_HNO3_NaOH', reactants:["HNO3","NaOH"], eq:'HNO3 + NaOH → NaNO3 + H2O', balanced:'HNO₃ + NaOH → NaNO₃ + H₂O', products:["NaNO3","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HNO3 with NaOH.', realUse:'Salt production' },
  { id:'auto_HNO3_KOH', reactants:["HNO3","KOH"], eq:'HNO3 + KOH → KNO3 + H2O', balanced:'HNO₃ + KOH → KNO₃ + H₂O', products:["KNO3","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HNO3 with KOH.', realUse:'Salt production' },
  { id:'auto_HNO3_LiOH', reactants:["HNO3","LiOH"], eq:'HNO3 + LiOH → LiNO3 + H2O', balanced:'HNO₃ + LiOH → LiNO₃ + H₂O', products:["LiNO3","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HNO3 with LiOH.', realUse:'Salt production' },
  { id:'auto_HNO3_Ca(OH)2', reactants:["HNO3","Ca(OH)2"], eq:'HNO3 + Ca(OH)2 → Ca(NO3)2 + H2O', balanced:'₂HNO₃ + Ca(OH)₂ → Ca(NO₃)₂ + ₂H₂O', products:["Ca(NO3)2","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HNO3 with Ca(OH)2.', realUse:'Salt production' },
  { id:'auto_HNO3_Mg(OH)2', reactants:["HNO3","Mg(OH)2"], eq:'HNO3 + Mg(OH)2 → Mg(NO3)2 + H2O', balanced:'₂HNO₃ + Mg(OH)₂ → Mg(NO₃)₂ + ₂H₂O', products:["Mg(NO3)2","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of HNO3 with Mg(OH)2.', realUse:'Salt production' },
  { id:'auto_H2SO4_NaOH', reactants:["H2SO4","NaOH"], eq:'H2SO4 + NaOH → Na2SO4 + H2O', balanced:'H₂SO₄ + ₂NaOH → Na₂SO₄ + ₂H₂O', products:["Na2SO4","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of H2SO4 with NaOH.', realUse:'Salt production' },
  { id:'auto_H2SO4_KOH', reactants:["H2SO4","KOH"], eq:'H2SO4 + KOH → K2SO4 + H2O', balanced:'H₂SO₄ + ₂KOH → K₂SO₄ + ₂H₂O', products:["K2SO4","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of H2SO4 with KOH.', realUse:'Salt production' },
  { id:'auto_H2SO4_LiOH', reactants:["H2SO4","LiOH"], eq:'H2SO4 + LiOH → Li2SO4 + H2O', balanced:'H₂SO₄ + ₂LiOH → Li₂SO₄ + ₂H₂O', products:["Li2SO4","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of H2SO4 with LiOH.', realUse:'Salt production' },
  { id:'auto_H2SO4_Ca(OH)2', reactants:["H2SO4","Ca(OH)2"], eq:'H2SO4 + Ca(OH)2 → CaSO4 + H2O', balanced:'H₂SO₄ + Ca(OH)₂ → CaSO₄ + ₂H₂O', products:["CaSO4","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of H2SO4 with Ca(OH)2.', realUse:'Salt production' },
  { id:'auto_H2SO4_Mg(OH)2', reactants:["H2SO4","Mg(OH)2"], eq:'H2SO4 + Mg(OH)2 → MgSO4 + H2O', balanced:'H₂SO₄ + Mg(OH)₂ → MgSO₄ + ₂H₂O', products:["MgSO4","H2O"], type:'acid-base', visual:'dissolve', color:'hsl(200,50%,70%)', enthalpy:-55, desc:'Neutralization of H2SO4 with Mg(OH)2.', realUse:'Salt production' },
  { id:'auto_CH4_combust', reactants:["CH4","O2"], eq:'CH4 + O2 → CO2 + H2O', balanced:'Combustion of CH4', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of CH4.', realUse:'Energy generation' },
  { id:'auto_C2H6_combust', reactants:["C2H6","O2"], eq:'C2H6 + O2 → CO2 + H2O', balanced:'Combustion of C2H6', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of C2H6.', realUse:'Energy generation' },
  { id:'auto_C3H8_combust', reactants:["C3H8","O2"], eq:'C3H8 + O2 → CO2 + H2O', balanced:'Combustion of C3H8', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of C3H8.', realUse:'Energy generation' },
  { id:'auto_C4H10_combust', reactants:["C4H10","O2"], eq:'C4H10 + O2 → CO2 + H2O', balanced:'Combustion of C4H10', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of C4H10.', realUse:'Energy generation' },
  { id:'auto_C5H12_combust', reactants:["C5H12","O2"], eq:'C5H12 + O2 → CO2 + H2O', balanced:'Combustion of C5H12', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of C5H12.', realUse:'Energy generation' },
  { id:'auto_C6H14_combust', reactants:["C6H14","O2"], eq:'C6H14 + O2 → CO2 + H2O', balanced:'Combustion of C6H14', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of C6H14.', realUse:'Energy generation' },
  { id:'auto_C7H16_combust', reactants:["C7H16","O2"], eq:'C7H16 + O2 → CO2 + H2O', balanced:'Combustion of C7H16', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of C7H16.', realUse:'Energy generation' },
  { id:'auto_C8H18_combust', reactants:["C8H18","O2"], eq:'C8H18 + O2 → CO2 + H2O', balanced:'Combustion of C8H18', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of C8H18.', realUse:'Energy generation' },
  { id:'auto_C9H20_combust', reactants:["C9H20","O2"], eq:'C9H20 + O2 → CO2 + H2O', balanced:'Combustion of C9H20', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of C9H20.', realUse:'Energy generation' },
  { id:'auto_C10H22_combust', reactants:["C10H22","O2"], eq:'C10H22 + O2 → CO2 + H2O', balanced:'Combustion of C10H22', products:["CO2","H2O"], type:'combustion', visual:'fire', color:'hsl(0,0%,90%)', enthalpy:-2000, desc:'Combustion of C10H22.', realUse:'Energy generation' },
  { id:'auto_Fe_O2', reactants:["Fe","O2"], eq:'Fe + O2 → FexOy', balanced:'Oxidation of Fe', products:["Fe Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Fe.', realUse:'Material degradation' },
  { id:'auto_Cu_O2', reactants:["Cu","O2"], eq:'Cu + O2 → CuxOy', balanced:'Oxidation of Cu', products:["Cu Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Cu.', realUse:'Material degradation' },
  { id:'auto_Zn_O2', reactants:["Zn","O2"], eq:'Zn + O2 → ZnxOy', balanced:'Oxidation of Zn', products:["Zn Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Zn.', realUse:'Material degradation' },
  { id:'auto_Al_O2', reactants:["Al","O2"], eq:'Al + O2 → AlxOy', balanced:'Oxidation of Al', products:["Al Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Al.', realUse:'Material degradation' },
  { id:'auto_Mg_O2', reactants:["Mg","O2"], eq:'Mg + O2 → MgxOy', balanced:'Oxidation of Mg', products:["Mg Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Mg.', realUse:'Material degradation' },
  { id:'auto_Ni_O2', reactants:["Ni","O2"], eq:'Ni + O2 → NixOy', balanced:'Oxidation of Ni', products:["Ni Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Ni.', realUse:'Material degradation' },
  { id:'auto_Co_O2', reactants:["Co","O2"], eq:'Co + O2 → CoxOy', balanced:'Oxidation of Co', products:["Co Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Co.', realUse:'Material degradation' },
  { id:'auto_Mn_O2', reactants:["Mn","O2"], eq:'Mn + O2 → MnxOy', balanced:'Oxidation of Mn', products:["Mn Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Mn.', realUse:'Material degradation' },
  { id:'auto_Cr_O2', reactants:["Cr","O2"], eq:'Cr + O2 → CrxOy', balanced:'Oxidation of Cr', products:["Cr Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Cr.', realUse:'Material degradation' },
  { id:'auto_Ti_O2', reactants:["Ti","O2"], eq:'Ti + O2 → TixOy', balanced:'Oxidation of Ti', products:["Ti Oxide"], type:'oxidation', visual:'color-change', color:'hsl(0,0%,50%)', enthalpy:-500, desc:'Oxidation of Ti.', realUse:'Material degradation' },
];

function stringify(obj) {
    return JSON.stringify(obj, null, 2).replace(/"([^"]+)":/g, '$1:').replace(/"/g, "'");
}

let addedStr = lostReactions.map(stringify).join(',\n  ');

let newContent = content.substring(0, reactionsStartIndex) + 
                 '\n  ' + addedStr + ',\n' +
                 content.substring(reactionsStartIndex);

fs.writeFileSync(filePath, newContent);
console.log('Restored some lost reactions');
